### ISSUE TITLE
Removed residence persist in ResidenceList

### ISSUE THREAD

**Issue by TiaTheFairy** [ArtformGames/ResidenceList#32]
### **Description**

After player removed his residence. The data persists in ResidenceList. Logging errors when server starts up.

### **Operatios**

1. Player removed his residence.
2. When server starts. It logs errors.

### **Screenshots & Error Logs**
![Snipaste_2024-03-10_22-52-26](https://github.com/ArtformGames/ResidenceList/assets/69950541/9866f4f4-b005-401c-85d6-69c47507501c)

### **Environment**

- System: `Windows 10` / `Ubuntu` / `...`
- Java version: `JDK11` / `OPENJDK8` / `JRE8` / `...`

**Comment by CarmJos** [comment]
Thanks for your reporting! Please try the artifacts in https://github.com/ArtformGames/ResidenceList/actions/runs/8222911904 and check if the problem has been solved.

Notice: this version will not purge the deleted residences while loading to prevent data-losing, so you may need to remove deleted residence by yourself.

**Comment by CarmJos** [comment]
If tested, please tell me the results, thanks for you help!

**Comment by Sraconni** [comment]
Hi TiaTheFairy, after self-tested, this [snapshot assets](https://github.com/ArtformGames/ResidenceList/actions/runs/8222911904/artifacts/1312962178) has solved the problem you reported and works. 

I will close the issue since you have not responded for a long time, If you still have any problems about this, please reopen the issue.
